// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2VLcR(std::string::String);
impl z2VLcR {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2Vdrd {z2VSUE , z2VbGP ,} 
pub struct z2VM6S(std::string::String);
impl z2VM6S {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VMpT(std::string::String);
impl z2VMpT {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VL1B {z2Vbo1 , z2Vddi , z2VNj5 , z2VWCY , z2Vaps , z2VSk9 , z2VTsb ,} 
pub struct z2VS1N(std::string::String);
impl z2VS1N {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VUiY {z2VZ3Y , z2VUm4 ,} 
